version: "3.7"

services:
    plain-apache:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html/
        restart: always
        networks: 
            - "reverse-proxy-net"
networks:
  reverse-proxy-net:
    external: true
