version: "3.7"

services:
    plain-apache:
        #container_name: plain-apache
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html/
        restart: always
        networks: 
            - "reverse-proxy-net"
        expose:
            - "5000"
        #ports:
        #  - "81:80"
networks:
  reverse-proxy-net:
    external: true
