version: "3.7"

services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        environment:
            VIRTUAL_HOST: memorygrid.localhost 
            LETSENCRYPT_HOST: memorygrid.localhost 
            VIRTUAL_PORT: 80
        networks: 
            - "reverse-proxy-net"
        volumes:
            - ./:/var/www/html/     
    db:
        #Container name must be host name for mysqli connection (at least locally)
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: memorygrid
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        networks: 
            - "reverse-proxy-net"
        ports:
            - "9906:3306"

networks:
  reverse-proxy-net:
    external: true