version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: "reverse-proxy"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./proxy.conf:/etc/nginx/proxy.conf:ro
        - /home-link/sebdw02/certs:/etc/nginx/certs
    restart: "always"
    networks: 
        - "reverse-proxy-net"
    ports:
        - "80:80"
        - "443:443"


volumes:
  certs:

networks:
  reverse-proxy-net:
    external: true