version: "3.7"

services:
    plain-php:
        #container_name: plain-apache
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html/
        restart: always
        networks: 
            - "reverse-proxy-net"
        expose:
            - "9000"
networks:
  reverse-proxy-net:
    external: true
