version: "3.7"

services:
    plain-apache-environment:
        container_name: plain-apache
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html/
        environment:
            VIRTUAL_HOST: plain-apache.localhost 
            LETSENCRYPT_HOST: plain-apache.localhost 
            VIRTUAL_PORT: 80
        networks: 
            - "reverse-proxy-net"
networks:
  reverse-proxy-net:
    external: true
