version: "3.7"
#https://www.section.io/engineering-education/dockerized-php-apache-and-mysql-container-development-environment/
services:
    #Adapt the service and container names to be unique for your project        
    php-apache-environment-2:
        container_name: php-apache-2
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db-2
        environment:
            VIRTUAL_HOST: memorygrid.localhost 
            LETSENCRYPT_HOST: memorygrid.localhost 
            VIRTUAL_PORT: 80
        networks: 
            - "reverse-proxy-net"
        volumes:
            - ./:/var/www/html/
        #ports:
        #  - "8000:80"
    db-2:
        #Service name must be host name for mysqli connection (at least locally)
        container_name: db-2
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        networks: 
            - "reverse-proxy-net"
        ports:
            - "9906:3306"
    phpmyadmin:
        #https://hub.docker.com/_/phpmyadmin?tab=description
        image: phpmyadmin/phpmyadmin
        #ports:
        #    - '8080:80'
        restart: always
        environment:
            PMA_HOST: db-2
            VIRTUAL_HOST: phpmyadmin.localhost 
            LETSENCRYPT_HOST: phpmyadmin.localhost 
            VIRTUAL_PORT: 80
        networks: 
            - "reverse-proxy-net"
        depends_on:
            - db-2
networks:
  reverse-proxy-net:
    external: true