version: "3.7"
#https://www.section.io/engineering-education/dockerized-php-apache-and-mysql-container-development-environment/
services:
    #Adapt the service and container names to be unique for your project        
    php-2:
        container_name: php-apache-2
        build:
            context: ./
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - db-2
        networks: 
            - "reverse-proxy-net"
        volumes:
            - ./:/var/www/html/
    db-2:
        #Service name must be host name for mysqli connection (at least locally)
        #container_name: db-2
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_phpMyadmin
            MYSQL_USER: test_phpMyadmin
            MYSQL_PASSWORD: test_phpMyadmin
        networks: 
            - "reverse-proxy-net"
    phpmyadmin:
        #https://hub.docker.com/_/phpmyadmin?tab=description
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: db-2
            PMA_ABSOLUTE_URI: https://memo.hib.uni-tuebingen.de/database/
        networks: 
            - "reverse-proxy-net"
        depends_on:
            - db-2
networks:
  reverse-proxy-net:
    external: true
