version: '2'

services:
  whoami:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8000
      - VIRTUAL_PATH=/whoami-2
    networks: 
      - "reverse-proxy-net"

networks:
  reverse-proxy-net:
    external: true