version: "3.7"

services:
    php-1:
        container_name: php-apache-1
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        restart: always
        networks: 
            - "reverse-proxy-net"
        volumes:
            - ./:/var/www/html/
    db-1:
        #Container name must be host name for mysqli connection (at least locally)
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        networks: 
            - "reverse-proxy-net"

networks:
  reverse-proxy-net:
    external: true
